apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver-api
  template:
    metadata:
      labels:
        app: webserver-api
    spec:
      containers:
      - name: webserver-api
        image: stevenewald/ha_db_webserver:latest
        ports:
        - containerPort: 3000
        env:
          - name: AWS_REGION
            value: us-east-2
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: secret-access-key
